#!/bin/sh

set -e

# get the database path
db_path=$(
    grep ^db_path /home/user/config/config.toml | \
    cut -d= -f2- | \
    sed -E -e 's/^\s+//g' -e 's/\s+$//g' -e 's/^"//' -e 's/"$//'
)

# set up the database
/usr/local/cargo/bin/diesel --database-url "${db_path}" setup --migration-dir "/home/user/registration_server/migrations/{{db_type}}"

# get the initial GeoIP database
/usr/bin/geoipupdate

# run all of our background services
exec /usr/bin/runsvdir /etc/service
